#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
    exit 1
fi

failinimi=$1

if [ -f "$failinimi" ] && [ -r "$failinimi" ]; then
    for rida in $(cat "$failinimi"); do
	KASUTAJA=$(echo "$rida" | cut -f1 -d:)
	echo "Lisan kasutajat: $KASUTAJA"
        ./lisa_kasutaja "$KASUTAJA"
	echo "$rida" | sudo chpasswd
        if [ $? -ne 0 ]; then
            echo "Kasutaja lisamine ebaõnnestus: $nimi"
        fi
    done
else
    echo "Probleem failiga $failinimi: Fail ei eksisteeri või ei ole loetav"
fi
