#!/bin/bash

# skript kontrollib kas kasutaja eksisteerib ning loob kasutaja; lisab vajalikud failid
# ja oigused

if [ -z "$1" ]; then
    echo "Viga: Kasutajanimi ei ole antud!"
    echo "Kasutamine: $0 <kasutajanimi>"
    exit 1
fi

KASUTAJA=$1

if id "$KASUTAJA" &>/dev/null; then
    echo "Kasutaja $KASUTAJA juba eksisteerib!"
    exit 1
fi

sudo useradd $KASUTAJA -m -s /bin/bash
if [ $? -ne 0 ]; then
    echo "Kasutaja loomine ebaõnnestus!"
    echo "Veakood $?"
    exit 1
fi

echo "Kasutaja $KASUTAJA on edukalt loodud!"
